services:
  - type: pserv
    name: ninja
    env: Docker
    numInstances: 1
    dockerfilePath: Dockerfile
    image: gngpp/ninja:latest
    envVars:
    - key: TZ
      value: Asia/Shanghai 
    - key: PROXIES
      value: socks5://warp:10000
  - type: pserv
    name: warp
    env: Docker
    numInstances: 1
    dockerfilePath: Dockerfile
    image: ghcr.io/gngpp/warp:latest
  - type: pserv
    name: watchtower
    env: Docker
    numInstances: 1
    dockerfilePath: Dockerfile
    image: containrrr/watchtower
